apiVersion: v1
kind: Pod
metadata:
  name: linux-learner-pod
  labels:
    role: linux-learner-pod
spec:
  containers:
    - name: postgres
      image: docker.io/library/postgres:16
      imagePullPolicy: IfNotPresent
      env:
        - name: POSTGRES_DB
          value: linuxlearner
        - name: POSTGRES_PASSWORD
          value: linuxlearner
        - name: POSTGRES_USER
          value: linuxlearner
      ports:
        - containerPort: 5432
          protocol: TCP
          hostPort: 8000
      restartPolicy: Always
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
    - name: keydb
      image: docker.io/eqalpha/keydb
      ports:
        - containerPort: 6379
          protocol: TCP
          hostPort: 8001
      command:
        - "keydb-server"
      args:
        - "--appendonly"
        - "yes"
      volumeMounts:
        - mountPath: /data
          name: keydb-data
    - name: keycloak
      image: quay.io/keycloak/keycloak:24.0.5
      args:
        - start-dev
      env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
      ports:
        - containerPort: 8080
          protocol: TCP
          hostPort: 8002
      restartPolicy: Always
      volumeMounts:
        - mountPath: /opt/keycloak/data/h2
          name: keycloak-data
  volumes:
    - name: postgresql-data
      hostPath:
        path: .volumes/postgresql-data
    - name: keydb-data
      hostPath:
        path: .volumes/keydb-data
    - name: keycloak-data
      hostPath:
        path: .volumes/keycloak-data
