# Obtain token for student
POST {{keycloak}}/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{keycloak-client-id}}&client_secret={{keycloak-client-secret}}&username={{keycloak-student-username}}&password={{keycloak-password}}

> {% 
client.global.set("student-token", response.body["access_token"]);
 %}
###

# Obtain token for teacher
POST {{keycloak}}/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{keycloak-client-id}}&client_secret={{keycloak-client-secret}}&username={{keycloak-teacher-username}}&password={{keycloak-password}}

> {% 
client.global.set("teacher-token", response.body["access_token"]);
 %}
###

# Obtain token for other teacher
POST {{keycloak}}/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{keycloak-client-id}}&client_secret={{keycloak-client-secret}}&username={{keycloak-another-teacher-username}}&password={{keycloak-password}}

> {%
    client.global.set("another-teacher-token", response.body["access_token"]);
%}
###
