# Create a course
POST {{teacher-api}}/courses
Authorization: Bearer {{teacher-token}}
Content-Type: application/json

{
  "name": "Mah jerb course",
  "description": "Mah description",
  "acceptanceMode": "NoInviteRequired"
}
###

// Force-delete a course
DELETE {{admin-api}}/courses/7476a102-2be1-40ee-8018-6b1189640bd0/force
Authorization: Bearer {{admin-token}}
Content-Type: application/json
###

// Delete own participation
DELETE {{student-api}}/participations/course/e663b67c-73a0-4bc1-8901-d307e9874ea2/user/self
Authorization: Bearer {{teacher-token}}
###

// Create invite for course
POST {{teacher-api}}/courses/dad7a77a-5464-4406-8401-035d51a1e5a4/invites
Authorization: Bearer {{teacher-token}}
Content-Type: application/json

{
  "usageLimit": 10
}
###

// Get invite for course
GET {{teacher-api}}/courses/dad7a77a-5464-4406-8401-035d51a1e5a4/invites/b193f21e-65e4-424d-ab3f-64707623ceef
Authorization: Bearer {{teacher-token}}
###

// Patch invite for course
PATCH {{teacher-api}}/courses/dad7a77a-5464-4406-8401-035d51a1e5a4/invites/b193f21e-65e4-424d-ab3f-64707623ceef
Authorization: Bearer {{teacher-token}}
Content-Type: application/json

{
  "usageLimit": 55
}
