// Create course
POST {{api}}/courses
Authorization: Bearer {{teacher-token}}
Content-Type: application/json

{
  "name": "My course name",
  "description": "Sample description",
  "acceptanceMode": "InviteRequired"
}
###

// Retrieve course
GET {{api}}/courses/cc3d9933-6e1a-4347-b69d-0229c4da4eee
Authorization: Bearer {{student-token}}
###

// Partially modify course
PATCH {{api}}/courses/cc3d9933-6e1a-4347-b69d-0229c4da4eee
Authorization: Bearer {{student-token}}
Content-Type: application/json

{
  "description": "new fancy desc"
}
###

// Delete course
DELETE {{api}}/courses/cc3d9933-6e1a-4347-b69d-0229c4da4eee
Authorization: Bearer {{teacher-token}}
